package ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0961a4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd1e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001c37)
val md_theme_light_secondary = Color(0xFF535f70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd6e3f7)
val md_theme_light_onSecondaryContainer = Color(0xFF101c2b)
val md_theme_light_tertiary = Color(0xFF6b5678)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf4daff)
val md_theme_light_onTertiaryContainer = Color(0xFF251431)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF1b1b1b)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1b1b1b)
val md_theme_light_surfaceVariant = Color(0xFFdfe3ec)
val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
val md_theme_light_outline = Color(0xFF73777f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3033)
val md_theme_light_inversePrimary = Color(0xFF9ecaff)

val md_theme_dark_primary = Color(0xFF9ecaff)
val md_theme_dark_onPrimary = Color(0xFF00325b)
val md_theme_dark_primaryContainer = Color(0xFF00487f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd1e4ff)
val md_theme_dark_secondary = Color(0xFFbbc7db)
val md_theme_dark_onSecondary = Color(0xFF253140)
val md_theme_dark_secondaryContainer = Color(0xFF3c4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e3f7)
val md_theme_dark_tertiary = Color(0xFFd7bde4)
val md_theme_dark_onTertiary = Color(0xFF3b2947)
val md_theme_dark_tertiaryContainer = Color(0xFF523f5e)
val md_theme_dark_onTertiaryContainer = Color(0xFFf4daff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1b)
val md_theme_dark_onBackground = Color(0xFFe2e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1b)
val md_theme_dark_onSurface = Color(0xFFe2e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF43474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7d0)
val md_theme_dark_outline = Color(0xFF8d9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1b)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)
val md_theme_dark_inversePrimary = Color(0xFF0961a4)

fun getBackgroundColor(isDarkTheme: Boolean): Triple<Double, Double, Double> {
    val color = if (isDarkTheme) darkColorScheme().background else lightColorScheme().background
    return Triple(color.red.toDouble(), color.green.toDouble(), color.blue.toDouble())
}
